/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        neon: '#4f46e5',
        neon2: '#9089fc',
        gold: '#ff80b5',
        dark: '#111827',
      },
      fontFamily: {
        syne: ['Syne', 'sans-serif'],
        grotesk: ['"Space Grotesk"', 'sans-serif'],
      },
      animation: {
        'grid-move': 'gridMove 20s linear infinite',
        'orb-float-1': 'orbFloat1 8s ease-in-out infinite',
        'orb-float-2': 'orbFloat2 10s ease-in-out infinite',
        'orb-float-3': 'orbFloat3 12s ease-in-out infinite',
        'fade-up': 'fadeUp 0.8s both',
        'float-1': 'float1 4s ease-in-out infinite',
        'float-2': 'float2 5s ease-in-out infinite 0.5s',
        'float-3': 'float3 4.5s ease-in-out infinite 1s',
        'float-4': 'float4 5.5s ease-in-out infinite 0.3s',
        'slide-down': 'slideDown 0.8s ease both',
        'marquee': 'marquee 20s linear infinite',
        'blink': 'blink 0.8s step-end infinite',
        'pop-in': 'popIn 0.5s both',
        'code-fade': 'codeFadeIn 0.4s both',
        'line-grow': 'lineGrow 1s 0.8s both',
        'pulse-dot': 'pulseDot 1.5s ease infinite',
      },
      keyframes: {
        gridMove: { '0%': { transform: 'translateY(0)' }, '100%': { transform: 'translateY(60px)' } },
        orbFloat1: { '0%,100%': { transform: 'translate(0,0) scale(1)' }, '50%': { transform: 'translate(40px,30px) scale(1.1)' } },
        orbFloat2: { '0%,100%': { transform: 'translate(0,0) scale(1)' }, '50%': { transform: 'translate(-30px,-40px) scale(0.9)' } },
        orbFloat3: { '0%,100%': { transform: 'translate(-50%,-50%) scale(1) rotate(0deg)' }, '50%': { transform: 'translate(-50%,-50%) scale(1.2) rotate(180deg)' } },
        fadeUp: { from: { opacity: '0', transform: 'translateY(24px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideDown: { from: { opacity: '0', transform: 'translateY(-20px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        float1: { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-10px)' } },
        float2: { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-14px)' } },
        float3: { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-8px)' } },
        float4: { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-12px)' } },
        marquee: { from: { transform: 'translateX(0)' }, to: { transform: 'translateX(-50%)' } },
        blink: { '50%': { borderColor: 'transparent' } },
        popIn: { from: { opacity: '0', transform: 'scale(0.8)' }, to: { opacity: '1', transform: 'scale(1)' } },
        codeFadeIn: { from: { opacity: '0', transform: 'translateX(-8px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        lineGrow: { from: { transform: 'scaleX(0)' }, to: { transform: 'scaleX(1)' } },
        pulseDot: { '0%,100%': { opacity: '1', transform: 'scale(1)' }, '50%': { opacity: '0.5', transform: 'scale(1.5)' } },
      },
    },
  },
  plugins: [],
}
